### ISSUE TITLE
ISSUE: Re-enable outlining of aliasmodels

### ISSUE THREAD

**Issue by meag** [QW-Group/ezquake-source#456]
**Is your feature request related to a problem? Please describe.**
Everyone loves `gl_outline 1`
It relies on a z-offset adjustment that results in this becoming wallhack on certain cards & drivers (demonstrated by VVD)
Was removed in competitive rulesets for 3.2
Was re-added for 3.2.2 for thunderdome at VVD's request

**Describe the solution you'd like**
An implementation that doesn't result in wallhack
Everyone to stop bugging me to put it back in

**Comment by meag** [comment]
[19:33]lurq:@meag pretty sure some 5-series nvidia have the same problem
[19:34]lurq:my 275 and 680 doesn't have it

![image](https://user-images.githubusercontent.com/10936291/101995530-7a69ad00-3cc2-11eb-8ac9-891f34e86797.png)

^ example given by VVD, also tested with me standing behind pillar at ring and he confirmed he could see me

**Comment by meag** [comment]
Various discord snippets

![image](https://user-images.githubusercontent.com/10936291/101995600-f82db880-3cc2-11eb-8a90-15b5ba514ec7.png)
![image](https://user-images.githubusercontent.com/10936291/101995606-05e33e00-3cc3-11eb-92ef-7ab136124cbe.png)
![image](https://user-images.githubusercontent.com/10936291/101995663-a20d4500-3cc3-11eb-8608-fe87838f5a04.png)
![image](https://user-images.githubusercontent.com/10936291/101995670-b7826f00-3cc3-11eb-92ee-919d94af1c04.png)
![image](https://user-images.githubusercontent.com/10936291/101995684-d123b680-3cc3-11eb-8c5f-81fe78b127c5.png)
![image](https://user-images.githubusercontent.com/10936291/101995695-fb757400-3cc3-11eb-9e79-61168be7f6a1.png)

**Comment by dirtboxqw** [comment]
I have a PC here with an Nvidia GTX 560 in it so I can test this for you. Just let me know which client version(s) I should use to perform the tests for you.

**Comment by meag** [comment]
https://github.com/ezQuake/ezquake-source/commit/9965dfedaa9305ea20b2502abf241840363cda7b

Waiting for feedback
@dirtboxqw I'll look out VVD's config, should be on the old PC

**Comment by VVD** [comment]
AFAIR, it was several years ago on ezQ 2.1 with GF6600 AGP + NVIDIA blob 304.

**Comment by tcsabina** [comment]
This is probably fixed already. closing.
