### ISSUE TITLE
REQ: Restore Support for Joystick Input

### ISSUE THREAD

**Issue by ewhac** [QW-Group/ezquake-source#566]
Please ensure that your request is predominantly client-based, and not better suited to being logged with the server or mod aspects of QuakeWorld (e.g. mvdsv or ktx)

**Is your feature request related to a problem? Please describe.**
EZQuake used to support joystick input.  When platform-specific code was deleted in 2013 in favor of using SDL, joystick support was deleted with it and not converted over.

**Describe the solution you'd like**
Restore support for proportional joystick input.

**Describe alternatives you've considered**
None.  Utilities that map joystick deflections to button presses lose the fine proportional control only native joystick support can offer.

**Additional context**
Obviously, nobody plays Quake with a joystick/game controller.  However, *spectating* with a joystick, particularly a 6DOF controller such as a Spaceball or SpaceMouse, is really sweet.  That experience is what I'd like to restore.

I have already written this using SDL interfaces, and can put together a pull request.

**Impact on server or mods**
None anticipated.

**Comment by ewhac** [comment]
#567 is a proposed implementation, which is basically the original code pulled from Git history and updated for SDL, and should be drop-in compatible with old config files that still have joystick commands in them.

However, Quake's joystick setup was always rather klunky, so there's an opportunity here to make it nicer.  Any thoughts on the topic?

**Comment by meag** [comment]
Hi @ewhac 

Thanks for working on this, it has been requested before and makes the game more accessible too.  My main PC isn't hooked up at the moment but I've got some joysticks (or things that SDL2 thinks are joysticks, at least) to test with, will have a proper look at the weekend.

Thanks,
meag

**Comment by tcsabina** [comment]
Closing as the PR is merged, and there are some positive feedbacks on Discord about the implementation.
