### ISSUE TITLE
REQ: support for lit water (`-splitturb` in QBSP) [mapping]

### ISSUE THREAD

**Issue by inf1niti** [QW-Group/ezquake-source#631]
**Is your feature request related to a problem? Please describe.**
Other quake engines have recently moved to add support for `-splitturb` in QBSP, which allows for lighting in the map to effect water textures so they're not rendered as fullbrights.  This provides more natural looking lighting and enhances the visuals of maps.  

**Describe the solution you'd like**
Would be nice for EZQuake to support this feature and align with the rendering support that's happening in other engines.

**Additional context**
[implementation in QSS](https://github.com/Shpoike/Quakespasm/commit/4ec4cde5f4f157681de7d00ae2deb7c787bdd093)
**comparative screenshots:**
![image](https://user-images.githubusercontent.com/67801374/187233872-9823d936-6b54-4fb5-9399-c72f9ee70cd6.png)
![image](https://user-images.githubusercontent.com/67801374/187233928-84d43bac-69b1-4d16-b417-e24c4fec3e26.png)
![image](https://user-images.githubusercontent.com/67801374/187233975-7f407b0e-8fec-47a0-a366-293582f688ae.png)

**Impact on server or mods**
none.

**Comment by meag** [comment]
Can you supply an example .bsp file?

**Comment by inf1niti** [comment]
This flag was used when compiling the BSP I linked to in #629

**Comment by dsvensson** [comment]
> **Additional context** [implementation in QSS](https://github.com/Shpoike/Quakespasm/commit/4ec4cde5f4f157681de7d00ae2deb7c787bdd093) 

More examples:
[implementation in vQuake](https://github.com/Novum/vkQuake/commit/7b2e0e70bb004998831271308ef89ad27eb17826) (+ some bug fixes in later commits)
[implementation in QS](https://github.com/sezero/quakespasm/pull/35)

Those engines differ a bit from ezQuake, so does not look like a super trivial port for someone not well versed in GL/ezQuake architecture.

**Comment by tcsabina** [comment]
Solved with PR #716
