### ISSUE TITLE
REQ: easy way to copy variables to clipboard

### ISSUE THREAD

**Issue by HangTimeQW** [QW-Group/ezquake-source#645]
**Is your feature request related to a problem? Please describe.**
Sometimes I'm connected to a server, and want to copy and paste the IP somewhere else, e.g. telling teammates/enemies to gather there for a game.  Currently the only way to do this I am aware of is to refresh the server browser to find the server I am on and then use ctrl-C.  But this tells me that ezquake must at least have access to the clipboard and hence I'd like to make it quicker / more accessible.

**Describe the solution you'd like**
Implement a command that will copy the contents of a variable specified with an argument to the clipboard.  For example:
"/clipboard $serverip"

**Describe alternatives you've considered**
A less flexible option would be to not specify any arguments and just have a single command like "/copyserverip" that would do this for only serverip and no other variables.  This is sufficient for my primary use case but there might be other use cases that could benefit from being able to specify any variable.

**Comment by tcsabina** [comment]
Added with #821
