### ISSUE TITLE
GitHub Actions support?

### ISSUE THREAD

**Issue by dsvensson** [QW-Group/ezquake-source#650]
Curious if you'd be interested in adding GitHub Actions CI which would make it easier for collaborators to have CI up and running.

I've added a basic workflow to my repo for producing Linux and Windows builds with features waiting to be merged upstream. If there's interest it would be trivial to extend it to support the rest of the stuff the Azure pipeline does.

Sample:
https://github.com/qw-ctf/ezquake-source/actions/runs/2177183719

**Comment by tcsabina** [comment]
I think we can close this, right?
There is a basic pipeline now active, doing the Windows build with msbuild, just like on your example.
We dropped Linux builds, as that almost never works on "your" distro.
What might come in the future is an appimage build...

**Comment by dsvensson** [comment]
It doesn't cost anything to build for Linux as well. If someone is developing on Wintendo that may cause Linux build to fail. Also, would be great to use GitHub Actions artifacts if the build is not running in this repository's main branch, or is a PR. It doesn't cost anything, and lowers the threshold for trying out non-mainlined changes.

**Comment by dsvensson** [comment]
I added macOS arm builds to my downstream GA conf, perhaps repurpose this issue for that.

I've only tested launching single player start map, but seems to work. Someone who enjoys macOS should give it a go.

https://github.com/qw-ctf/ezquake-source/blob/d3f0c54d31eae91071e9574c1b35cbd0f2811559/.github/workflows/main.yml#L92-L137
