### ISSUE TITLE
REQ: new macro that outputs dates as yyyy.mm.dd

### ISSUE THREAD

**Issue by libTorrentUser** [QW-Group/ezquake-source#657]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to record a demo and it overwrites an existing one.

One way to avoid that is to append a timestamp to the demo file name, which is already supported, using something like `bind F12 "record $date-$mapname"`. The problem is that `$date` outputs the date as "day.month.year" which, although thankfully saner than "month.day.year" some countries insist on using, messes up the sorting by file name.

**Describe the solution you'd like**
Crate a macro named `$dateiso` which outputs an ISO 8601 like timestamp (yyyy.mm.ddTH.M.S). I can then use that to automatically name demos without having to worry about overwriting an existing file. 

**Describe alternatives you've considered**
Ideally, I would like to have something like the automatic match demo recording feature that could be enabled when playing single player/coop levels. Maybe something that could be triggered by a map change. If this is already possible, I wasn't able to figure out how to do it.

**Impact on server or mods**
None. But it would be great if servers auto-recorded MVDs when playing coop.

**Patches**
I've attached a patch that creates the `$dateiso` macro I was talking about. The patch will work for the latest release, but will needed a few changes to work with the latest commits in the master branch

[dateiso.patch.txt](https://github.com/ezQuake/ezquake-source/files/8693936/dateiso.patch.txt)
.

**Comment by tcsabina** [comment]
@libTorrentUser,

As you might have noticed, there is a PR that takes care of this feature request.
I've merged the PR today, so if you have a chance to test/verify the feature with one of the latest snapshots from https://builds.quakeworld.nu/ezquake/snapshots/, it would be awesome!

**Comment by tcsabina** [comment]
Probably closed with #771
