### ISSUE TITLE
REQ: -allowmultiple command line parameter on Windows shouldn't need a debug build

### ISSUE THREAD

**Issue by BLooD-DoG** [QW-Group/ezquake-source#677]
**Is your feature request related to a problem? Please describe.**
On linux (and presumably all other platforms besides Windows), running multiple instances of ezquake is supported "out of the box". Launching the executable starts a separate ezquake process if one is already running, so you have multiple clients running in parallel. This is helpful if you want to spec multiple games at the same time (and alt-tab between them), or you're trying to gather people for a 4on4 from different servers, or you're trying to develop/troubleshoot an issue and need multiple clients connected to a server. There isn't a performance impact as only the active window consumes resources.

On Windows, this is also possible but only if you run with the "-allowmultiple" command line parameter, AND only if you are using a debug build of ezquake. Adding a command line parameter is not a problem, but having a debug build isn't so obvious. Quite often people wonder how to launch multiple clients, there is confusion about how to obtain a debug vs non-debug build, questions about the performance impact of using a debug build, etc.

**Describe the solution you'd like**
Allow -allowmultiple in Windows even in non-debug builds, as there doesn't seem to be any reason to restrict -allowmultiple to only debug builds.

**Impact on server or mods**
None.

This is actually a very simple change, I can submit a PR shortly.

**Comment by blaps** [comment]
I concur.

**Comment by tcsabina** [comment]
PR #700 tackles this.
