### ISSUE TITLE
BUG: Player model is unaffected by gl_texturemode

### ISSUE THREAD

**Issue by zigg1zagg1** [QW-Group/ezquake-source#687]
**ezQuake version:**
3.6-alpha10 

**Describe the bug**
Player models appear to use `gl_linear` texture filtering regardless of what `gl_texturemode` is set to

**To Reproduce**
1. Set `noskins "1"`, `r_enemyskincolor ""` and `r_teamskincolor ""`
2. set `gl_texturemode "gl_nearest"`
3. see players still appearing with smooth texture filtering

**Comment by djleon83** [comment]
yes,this bug still in 3.6.1.
