### ISSUE TITLE
REQ: Spec feature - See through walls

### ISSUE THREAD

**Issue by blaps** [QW-Group/ezquake-source#711]
As a caster/streamer/qtv user, I'd like to get an even better understanding of the action, by seeing players positions as outlines/skeletons through walls, to be able to predict encounters and better follow the flow of the game. I would not want the feature permanently on, but rather have it on a button toggle and only show it in certain situations.

**Describe the solution you'd like**
An on-the-fly toggleable feature (that doesn't require vid_restart). 
It could have options for outline-width, color, gradient, and such. 
For teamplay, it would be helpful if there is a team/enemy color for the outlines.
Could there be a depth/distance setting, so that the feature only shows relevant players (read: being in relative proximity)?

**Describe alternatives you've considered**
Fill color instead of outline, but it might be too visually cluttering.
There should probably be a setting to include player names (scr_autoid) aswell. 

**Additional context**
Deepfake Photoshop Image1 - gradient outlines. 
![skeleton1](https://user-images.githubusercontent.com/8357443/205592613-23ae9fef-2db0-4bba-bb3c-c7ae0b4f14aa.jpg)
Deepfake Photoshop Image2 - single colored outlines.
![skeleton2](https://user-images.githubusercontent.com/8357443/205592616-0a4e9b8a-0f32-4499-9db1-ca9a47d90e9e.jpg)

**Comment by mushis** [comment]
Is there any technical challenge on this one?

I mean, FTE has something similar, not the outline, but the "health bubble"

**Comment by tcsabina** [comment]
Implemented with #800
