### ISSUE TITLE
BUG: in_raw 1 fails to initialize raw input mouse thread

### ISSUE THREAD

**Issue by badmofu** [QW-Group/ezquake-source#712]
**ezQuake version:**
Master build: `4010a7d2` on Apple Silicon M1
Also tested with same result with the latest binary from ezquake.com `3.6-dev-alpha10-dev`

**OS/device including version:**
iMac m1, Ventura 13.0.1

**Describe the bug**
Trying to set `in_raw 1` but ezquake fails to initialize mouse thread and falls back on SDL input. 
Input Monitoring in OSX settings is set.

`"failed to initialize raw input mouse thread"`

**To Reproduce**

1. Build ezquake from master (or download latest OSX binary from ezquake.com)
2. Allow ezquake binary, sh and terminal to monitoring input in OSX privacy settings
3. Try to set `in_raw 1`
4. See error `failed to initialize raw input mouse thread`

**Expected behavior**
Should switch to raw mouse input. Falls back on SDL instead, resulting in less than desirable mouse control.

**Screenshots**
default config

<img width="630" alt="Screenshot 2022-12-10 at 00 09 37" src="https://user-images.githubusercontent.com/29572/206810862-833f37cd-e7d0-4e81-9ef5-b4369cb6f9d6.png">

**Additional context**
Worked flawlessly on Intel iMac ;)

**Comment by mmaalouf** [comment]
Just tried on MacOS 12.6.1 Monterey with a MacBook Pro (ARM M1 Pro) and it worked fine for me with in_raw 1 and an external mouse. Could toggle back and forth between 1 and 0 without any errors, it initializes RAW or SDL mouse input.
ezQuake is version 3.6-dev-alpha10-dev r7198~6c0f2843 , also tried 3.6-dev-alpha10-antilag-r402
Not sure if it's related to you using Ventura 13.x, will see if I can upgrade and try.

**Comment by BLooD-DoG** [comment]
Just tried on MacOS 12.6.1 Monterey with a MacBook Pro (ARM M1 Pro) and it worked fine for me with in_raw 1 and an external mouse. Could toggle back and forth between 1 and 0 without any errors, it initializes RAW or SDL mouse input.
ezQuake is version 3.6-dev-alpha10-dev r7198~6c0f2843 , also tried 3.6-dev-alpha10-antilag-r402
Not sure if it's related to you using Ventura 13.x, will see if I can upgrade and try.

**Comment by badmofu** [comment]
@BLooD-DoG thanks! Any luck on your upgrade to Ventura?

**Comment by fzwoch** [comment]
You probably have to allow ezQuake for monitoring mouse and keyboard input in macOS Security and Privacy.

**Comment by fzwoch** [comment]
There has been a change where in_raw in macOS had the wrong initial value. However I don't think this is the issue being reported here.

I believe the issue is when you have enabled permission to read raw mouse input and then upgrade/change ezquake binary. The permissions are still set, but the new binary does not qualify for the existing set policy.

Unfortunately macOS does not re-show the permission dialog as technically it is already set. Removing the existing policy and then starting ezQuake should show the policy dialog. When accepted again it should allow to read raw mouse input. Until you change the ezQuake package again.

**Comment by badmofu** [comment]
I've this multiple times, with multiple binaries, I could easily force the policy dialog by removing the policy. Unfortunately, it always ended up with the same error in Ezquake. I've even tried wiping up all policies from the MacOS settings privacy policies, erasing all Ezquake binaries and downloading new ones. Still no success. I actually gave up trying, troubleshooting this via MacOS console or other system logs haven't helped. I might try with a fresh install of MacOS soon, but again I've downloaded Ezquake as a first thing when I've bought this M1 Mac, it was a fresh install in the beginning.

**Comment by BLooD-DoG** [comment]
I've tried again, this time while on MacOS 13.3 Ventura (my upgrade was delayed due to IT policies), and it's still working fine for me. I plugged in an external mouse, launched ezquake-darwin-arm, and I can toggle between in_mouse 0 and in_mouse 1 and both get "initialized" and the mouse input works in both. Not sure what else I can try to help you troubleshoot?

**Comment by BLooD-DoG** [comment]
Perhaps one difference is in the way I launch it? I never had luck with opening the ezQuake.app (either double clicking the file, or via `open ezQuake.app` in terminal). Instead, I copy the compiled binary to ezQuake.app/Contents/MacOs/ezquake-darwin-arm, then from the root nQuake folder `ln -s ezQuake.app/Contents/MacOS/ezquake-darwin-arm ezquake-arm` to symlink it, then run it from there in terminal with `./ezquake-darwin-arm`.

**Comment by badmofu** [comment]
Thanks again for the replies. I've just bough a new Mac (with M2 this time). EZquake was the first thing that was installed. Works like a charm :( Will need to dig, investigate more on why it still does not work on my previous machine. Perhaps I've had too many different EZquake binaries and the system got confused (can't revert that without reinstalling probably).

Anyhow, will close the case. Seems like only one of my machines is affected now. Thanks again!

**Comment by badmofu** [comment]
Closing the issue.
