### ISSUE TITLE
REQ: Combine the 2 outlining commands into one

### ISSUE THREAD

**Issue by tcsabina** [QW-Group/ezquake-source#713]
Currently there are 2 outlining related commands:
- gl_outline, which is responsible for the model outlines
- r_fx_geometry, which is responsible for the edge outlining of the walls

It needs to be combined into 1 command, which is also accessible from the Options menu

**Comment by HangTimeQW** [comment]
Why does it need to be 1 command?  They are two different things.

**Comment by tcsabina** [comment]
@HangTimeQW ,
I think I used wrong wording...
So I want all the outlining stuff controlled ny 1 command, like a toggle:
gl_outline 0, no outline
gl_outline 1, model outline
gl_outline 2, edge outline
gl_outline 3, model+edge outline

**Comment by HangTimeQW** [comment]
I think r_fx_geometry requires vid_framebuffer whereas gl_outline does not.  So might need some consideration like if someone wants gl_outline without framebuffer currently they can do that, but would that still be possible if the commands are merged?

**Comment by tcsabina** [comment]
Hello HT!

After some 2nd thoughts on the topic, maybe you are right...
I wanted to combine these outlining commands into one, to make it easier to handle (in the ezquake Options menu, and in rulesets), but at the end it is not an issue to leave them apart.
