### ISSUE TITLE
BUG: blood particles broken with fog

### ISSUE THREAD

**Issue by dsvensson** [QW-Group/ezquake-source#730]
Just like particle trails in #693, blood particles are broken as well. These are slightly different than other particles, so separate issue.

**Comment by dsvensson** [comment]
Heavy fog, fov 1, e1m1,

![image](https://user-images.githubusercontent.com/302027/212180023-9703e684-b443-4fae-856a-2aa2c1d8411b.png)

Unlike #693 where particles were completely blended away (?), here the blending issue is in the other direction where the transparent parts are kept.

**Comment by tcsabina** [comment]
Fixed with #729
