### ISSUE TITLE
BUG: local KTX doesn't work through gamedir command anymore.

### ISSUE THREAD

**Issue by madmentat86** [QW-Group/ezquake-source#740]
I use locally built KTX version to play with bots in standard modes. Was working fine up until last alpha, but with this release nothing happens when I do "gamedir ktx". Commands are not loaded.

**Comment by zigg1zagg1** [comment]
Its working for me on the latest build, make sure that if you're using a 32bit client that you also have a 32bit qwprogs for ktx
same goes for 64bit ones, they have to match

**Comment by madmentat86** [comment]
> Its working for me on the latest build, make sure that if you're using a 32bit client that you also have a 32bit qwprogs for ktx same goes for 64bit ones, they have to match

Hi zigg1, yeah, thank you for the answer. It looks like that's the issue indeed. The only problem is that current 3.6.1 release doesn't offer a x86 client at all and my qwprogs for ktx is 32bit.

**Comment by madmentat86** [comment]
closing as it's not a bug.
