### ISSUE TITLE
REQ: date/time shown on endgame scoreboard

### ISSUE THREAD

**Issue by mushis** [QW-Group/ezquake-source#772]
Would be nice to have the date and time shown on the endgame scoreboard.
So when any match is finished, scores are shown as usual, but also the date and time. I would suggest the position to be bottom center, but any is ok.

Nice to have: the date/time format could be customized.
Nice to have: while we're at it, add a hud element for it.

**Comment by blaps** [comment]
Much missed feature. Could also be a setting to print client version after date/time.

Why would you have date in hud? :) time already exists as an element. 
What I really miss tho, is the +showteamscores (what you see when you tab) as a hud element, but that's for a separate ticket.

**Comment by tcsabina** [comment]
Hi @mushis,

This has been added by PR #779. Please get a recent snapshot build from https://builds.quakeworld.nu/ezquake/snapshots/ and test it.

**Comment by mushis** [comment]
checked, working. 
Thanks
