### ISSUE TITLE
BUG: Linux binary build error

### ISSUE THREAD

**Issue by Slider-Whistle** [QW-Group/ezquake-source#782]
**ezQuake version:**
3aa908bd012f99a8a155155e7fe93f7b74156f3b

**OS/device including version:**
Gentoo

**Describe the bug**
Build is failing, appears somehow related to bundled minizip.
[ezqbuild.log](https://github.com/QW-Group/ezquake-source/files/11468611/ezqbuild.log)

**Comment by ciscon** [comment]
you want to install zlib with the minizip useflag and then disable the builtin minizip with USE_SYSTEM_MINIZIP=1 (you can throw that into .config)

**Comment by Slider-Whistle** [comment]
@ciscon Gave it a quick shot. Should this be right?
```
$ doas equery u sys-libs/zlib
doas (houston@mission-control) password:
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for sys-libs/zlib-1.2.13-r1:
 U I
 + + abi_x86_32  : 32-bit (x86) libraries
 + + minizip     : include the minizip library for quick and dirty zip extraction
 + + static-libs : Build static versions of dynamic libraries as well
 - - verify-sig  : Verify upstream signatures on distfiles
$ pwd
/home/houston/Git/github.com/QW-Group/ezquake-source
$ cat .config
USE_SYSTEM_MINIZIP=1
$ make clean
[CLEAN]
$ make
```
I seem to still be getting it. An strace seems to confirm that the file ".config" is being read.

**Comment by ciscon** [comment]
hrm, i haven't done it in a while but i remember that being all you had to do, what error are you getting exactly?

**Comment by Slider-Whistle** [comment]
Exactly the same one as in the first log, maybe the Makefile hasn't been fully convinced into using the system library somehow?

**Comment by ciscon** [comment]
i see what happened, the makefile got broken a bit.  i'll fix it but for now if you go to line 47 and remove the "-I$(SRC_DIR)/minizip" part, it should fix it.

**Comment by Slider-Whistle** [comment]
Okay, worked like a charm, game is running fine too. Glad the issue wasn't behind my keyboard this time, and to contribute in some way to this project. Don't know if I should close the issue, I'll just leave that to you.

**Comment by ciscon** [comment]
sure thing.  i'll close it out.
