### ISSUE TITLE
REQ: allow gl_outline 1 in ruleset smackdown

### ISSUE THREAD

**Issue by b1az3** [QW-Group/ezquake-source#799]
Please ensure that your request is predominantly client-based, and not better suited to being logged with the server or mod aspects of QuakeWorld (e.g. mvdsv or ktx)

**Is your feature request related to a problem? Please describe.**
Outline models look great but most players can't use it because it is blocked with ruleset smackdown or qcon.

**Describe the solution you'd like**
remove values 2 & 3 from gl_outline and allow the usage in ruleset smackdown. Outline of the world already covered by r_fx_geometry.
Alternatively, rename the cmd to gl_outline_models

**Describe alternatives you've considered**
No alternatives are available.

**Additional context**

**Impact on server or mods**

**Comment by tcsabina** [comment]
Hi b1az3,
This will not happen, sorry.
It has been discussed when we loosened up the allowance of gl_outline in some rulesets. But we have decided explicitly to not allow it in smackdown and qcon.

**Comment by b1az3** [comment]
Can you please share the reason?
As I understand it was some bug in the implementation which is not relevant anymore with r_fx_geometry.

**Comment by tcsabina** [comment]
Hey.
I was slightly mistaken: it is allowed in smackdown already since 3.6.2.

It is still disallowed in qcon, and will stay like that. That is a ruleset used in quakecon's competition, and we don't want any fancy stuff in it.
