### ISSUE TITLE
REQ: Port to pcre2

### ISSUE THREAD

**Issue by bgermann** [QW-Group/ezquake-source#815]
**Is your feature request related to a problem? Please describe.**
ezquake was autoremoved from Debian testing due to its pcre dependency.

**Describe the solution you'd like**
Please port to pcre2.

**Describe alternatives you've considered**
Make pcre optional or port to some other regex library.

**Additional context**
Debian bug report: https://bugs.debian.org/1000035

**Comment by tcsabina** [comment]
Probably closed with #816.
@bgermann , could you check if this would justify ezquake's presence in Debian testing?

**Comment by bgermann** [comment]
Yes, it would. Will there be a release soon?

**Comment by tcsabina** [comment]
@bgermann,
FYI,
https://www.quakeworld.nu/news/1188/ezquake-364-released
