### ISSUE TITLE
REQ: Remove checked in dependencies in favor of <package manager>

### ISSUE THREAD

**Issue by dsvensson** [QW-Group/ezquake-source#817]
Today the repo is polluted with:

* src/vstudio-libs
* src/mingw32-libs
* src/minizip
* src/opengl

In an ideal world it would be fine to rewrite history to avoid this mistake, but immutable hashes are :heart: 

Instead of embedding these dependencies ezQuake could instead use modern packaging systems such as Conan[^1] or vcpkg[^2]. The latter was recently more deeply integrated into Visual Studio[^3]. TrenchBroom is one example in the Quake sphere that uses vcpkg, see their [vcpkg.json](https://github.com/TrenchBroom/TrenchBroom/blob/master/vcpkg.json). It deals with static linking[^4], integrates well into CMake[^5] based builds when that time comes, and probably benefits the AppImage build as well.

As it is today the repo will continue to explode in size as dependencies are bumped or introduced. The new Vulkan backend will most likely want newer Vulkan stuff, and perhaps some other libraries, and the current set of libs in the repo are probably all sorts of vulnerable.

All aboard vcpkg? Yay? Nay? Alternatives?

[^1]: https://conan.io
[^2]: https://vcpkg.io
[^3]: https://devblogs.microsoft.com/cppblog/vcpkg-is-now-included-with-visual-studio/
[^4]: https://devblogs.microsoft.com/cppblog/vcpkg-updates-static-linking-is-now-available/
[^5]: https://learn.microsoft.com/en-us/vcpkg/users/buildsystems/cmake-integration

**Comment by Calinou** [comment]
I'd recommend going with vcpkg, though that likely also implies switching to CMake.
