### ISSUE TITLE
BUG: pcre2 port broke font listing

### ISSUE THREAD

**Issue by dsvensson** [QW-Group/ezquake-source#879]
Listing fonts results in "error code: 1", and no fonts listed. 

![image](https://github.com/QW-Group/ezquake-source/assets/302027/c8fa7ecb-3172-47c7-b200-838a77b6c13a)

**Comment by fzwoch** [comment]
Uh oh..

**Comment by qqshka** [comment]
should be fixed with recent mvdsv->ezquake sync, I did it in separate commit
