### ISSUE TITLE
BUG: glitchy text in the console

### ISSUE THREAD

**Issue by krizej** [QW-Group/ezquake-source#883]
**ezQuake version:** since 3.6.3 (possibly earlier - haven't tested)

**OS/device including version:**
arch linux 6.6.7-arch1-1, xorg
gpu: amd rx 6600 xt
driver: amdgpu
renderer: happens on both

**Describe the bug**
random lines appear mainly in the console but also sometimes randomly on-screen while in-game
does not happen on a clean config, i will try to find the broken cvar later

**To Reproduce**
1. use the attached config 
2. launch ezquake
3. open console and see glitchy text

**Screenshots**
![ezquake004](https://github.com/QW-Group/ezquake-source/assets/60076189/0fe462fd-0ae5-4073-a31c-37c3ba5623d3)
![ezquake005](https://github.com/QW-Group/ezquake-source/assets/60076189/e79ca125-ce39-460f-b2a0-f172eab3fd93)
[config.txt](https://github.com/QW-Group/ezquake-source/files/13745489/config.txt)

**Additional context**
does not happen on windows, and did not happen on linux before so i assume an updated driver/something caused this

**Comment by ciscon** [comment]
I have the feeling it's this: https://gitlab.freedesktop.org/mesa/mesa/-/issues/10353

**Comment by ciscon** [comment]
fiddling with various renderer options like vid_framebuffer you can minimize the effects, but there's always some little thing broken here or there randomly, the only way to completely mitigate it is to run everything through zink, which is an acceptable stop-gap solution until a mesa developer takes a look at it:

export MESA_LOADER_DRIVER_OVERRIDE=zink

**Comment by ciscon** [comment]
closing this out as it's now been fixed in mesa main (see above ticket)
