### ISSUE TITLE
BUG: con_notify_time dissapears before set value

### ISSUE THREAD

**Issue by mushis** [QW-Group/ezquake-source#917]
**ezQuake version:**
3.6.4 

**OS/device including version:**
Windows 10

**Describe the bug**
con_notify_time doesn't behave like expected.  I would expect the parameter meaning to be "seconds".

**To Reproduce**
Set one of these to a value higher than 10, and you will see it won't work properly.
```
con_notify_time 
hud_notify_time
```

I tested with 20, and timed it.
It dissapears at +-10 seconds, elapsed from my mobile chronometer app.

**Expected behavior**
It should be displayed for 20 seconds.

**Screenshots**
na

**Additional context**
na

**Comment by meag** [comment]
Hi mushi

This isn't a bug, it's limited at 10 seconds to stop cheaters using messages to time items.  For example during duels, filtering to mm2 only, and saying "took ra" then having it disappear 18 seconds later.

May 2016: https://github.com/QW-Group/ezquake-source/commit/f0882580e03c66fcc86a5e6023cebe35128a92cf

- meag

**Comment by mushis** [comment]
hey @meag ! 
thanks for clarification.
maybe it should be added to the allowed values in the description of the command.
